### ISSUE TITLE
attempt to index local 'node' (a nil value)

### ISSUE THREAD

**Issue by gennaro-tedesco** [SmiteshP/nvim-navbuddy#2] opened 2023-03-26 13:59 UTC
Good afternoon and thank you for always producing great plugins!

I am running
```
nvim --version
NVIM v0.9.0-dev-1290+g2257ade3d-dirty
```
and have installed the plugin via lazy.nvim (not that it matters); while attaching it to the language servers as per README (or alternatively by specifying 
```lua
lsp = {
        auto_attach = true, 
    }
```
I get the exception (upon invocation of `:Navbuddy`)
```lua
Error executing vim.schedule lua callback: ...re/nvim/lazy/nvim-navbuddy/lua/nvim-navbuddy/display.lua:75: attempt to index local 'node' (a nil value)
stack traceback:
	...re/nvim/lazy/nvim-navbuddy/lua/nvim-navbuddy/display.lua:75: in function 'fill_buffer'
	...re/nvim/lazy/nvim-navbuddy/lua/nvim-navbuddy/display.lua:366: in function 'redraw'
	...re/nvim/lazy/nvim-navbuddy/lua/nvim-navbuddy/display.lua:322: in function 'new'
	...share/nvim/lazy/nvim-navbuddy/lua/nvim-navbuddy/init.lua:217: in function 'handler'
	...share/nvim/lazy/nvim-navbuddy/lua/nvim-navbuddy/init.lua:165: in function 'handler'
	....local/share/nvim/lazy/nvim-navic/lua/nvim-navic/lib.lua:267: in function 'callback'
	...r/neovim/HEAD-2257ade/share/nvim/runtime/lua/vim/lsp.lua:2026: in function 'handler'
	...r/neovim/HEAD-2257ade/share/nvim/runtime/lua/vim/lsp.lua:1399: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
``` 
Subsequently also
```
Error detected while processing CursorMoved Autocommands for "<buffer=87>":
```
(or any other buffer number).

The line in question is [this one](https://github.com/SmiteshP/nvim-navbuddy/blob/61afbf6b2e7a86ff0c88a8535b51ea192146dfc7/lua/nvim-navbuddy/display.lua#L75) and the method in question is `node.parent`.

I notice there is a reference to `HEAD-2257ade` in the stack trace, latest commit on nightly, may that be the cause?

**Comment by SmiteshP** [comment] 2023-03-26 16:06
> I notice there is a reference to HEAD-2257ade in the stack trace, latest commit on nightly, may that be the cause?

Yeah that looks suspicious 🤔 . Also I noticed `dirty` added on to your version number, what does that mean? Mine is just showing `NVIM v0.9.0-dev-1290+g2257ade3dc`

Could you share some minimal C++, python or even lua file where you are able to recreate this issue? I am not able to reproduce it 😓 
Also just a hunch, could you try wrapping [this](https://github.com/SmiteshP/nvim-navbuddy/blob/master/lua/nvim-navbuddy/init.lua#L211) line in if not equal to nil check. Let me know if it helps.

**Comment by ColonelPhantom** [comment] 2023-03-26 16:06
I seem to be getting the same error in a Python file on Nvim 0.8.3 (with jedi language server). Haven't had the time to look at it more in-depth, though.

**Comment by yngwi** [comment] 2023-03-26 16:08
I've got the same error in Nvim Nightly from today with Typescript language server

**Comment by SmiteshP** [comment] 2023-03-26 16:18
Tried typescript server. got the error 👍🏽 
So my guess is that it is lsp server specific issue. Looking into it

**Comment by SmiteshP** [comment] 2023-03-26 16:35
Fixed the issue from nvim-navic side.
Can you guys update to latest nvim-navic and let me know if the issue if fixed?

**Comment by yngwi** [comment] 2023-03-26 16:56
I don't get the error any more! Thank you!

**Comment by sf8193** [comment] 2023-03-26 17:12
that fixed it for me as well! thanks, very promising plugin

**Comment by gennaro-tedesco** [comment] 2023-03-26 18:05
Updating fixes the error for me as well. As far as I am concern, we can close this issue as solved!

**Comment by ColonelPhantom** [comment] 2023-03-26 20:03
Seems to work here too!

**Comment by SmiteshP** [comment] 2023-03-27 02:28
Closing issue as problem is solved 🥳

**Closed by SmiteshP** 2023-03-27 02:28 UTC
Labels: bug
