### ISSUE TITLE
Can't load plugin on nvim 0.9.1

### ISSUE THREAD

**Issue by navxio** [SmiteshP/nvim-navbuddy#65] opened 2023-06-20 14:08 UTC
Getting error
```
Error detected while processing LspAttach Autocommands for "*":
E5108: Error executing lua vim/_editor.lua:0: LspAttach Autocommands for "*"..script nvim_exec2() called at LspAttach Autocommands for "*":0: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:118: LspAttach Autocommands for \"*\"..LspAttach Autocommands for \"*\": Vim(append):Error executing lua callback: ...ck/packer/start/nvim-navbuddy/lua/nvim-navbuddy/init.lua:367: attempt to index field 'data' (a nil value)
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:179: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:175>
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_exec_autocmds'
	...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1531: in function '_on_attach'
	...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1358: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

This is my config:

```
    use({
      "SmiteshP/nvim-navbuddy",
      requires = {
        "neovim/nvim-lspconfig",
        "SmiteshP/nvim-navic",
        "MunifTanjim/nui.nvim",
      },
      config = function()
        require("nvim-navbuddy").setup({
          icons = {
            buffer = "﬘",
            folder = "",
            lsp = "",
            git = "",
            error = "",
            warning = "",
            info = "",
            hint = "",
          },
          lsp = {
            auto_attach = true,
          },
          window = {
            border = "rounded",
          },
        })
      end,
    })
```

**Comment by SmiteshP** [comment] 2023-06-21 05:19
Duplicate of #64

**Closed by SmiteshP** 2023-06-21 05:19 UTC
